In [33]:
import numpy as np

In [34]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
evalues, evectors = np.linalg.eig(a)
print(evalues)
print(evectors)
print('\n',np.diag(evalues))
print('\n',np.linalg.inv(evectors))
print('\n',evectors.dot(np.diag(evalues)).dot(np.linalg.inv(evectors)))

[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]

 [[ 1.61168440e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.11684397e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -9.75918483e-16]]

 [[-0.48295226 -0.59340999 -0.70386772]
 [-0.91788599 -0.24901003  0.41986593]
 [ 0.40824829 -0.81649658  0.40824829]]

 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [49]:
x=np.array([1,2,3]).reshape(1,-1)
y=np.array([4,5,6]).reshape(-1,1)
print(x)
print(y)
print(y*x)
print(y.dot(x).dot(y))

[[1 2 3]]
[[4]
 [5]
 [6]]
[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]
[[128]
 [160]
 [192]]
