In [672]:
import numpy as np
import random

#### Fitness Function

In [673]:
def fitness(np):
    f=0
    for i in np:
        f=f+i
    return f

In [674]:
pop_size=6
ch_size=4
min_value=0
max_value=30
pc=0.4 #Crossover Rate
pm = 0.1 #Mutation Rate

#### Initialization

In [675]:
chromosomes = np.random.randint(min_value,max_value,size=(pop_size,ch_size))
print(chromosomes)

[[27 21 26 17]
 [21  6 10 22]
 [20 22  7 20]
 [14 14 24 12]
 [12 28 19 25]
 [29 12 17 14]]


#### Fitness Evaluation

In [676]:
f=np.zeros(pop_size,dtype='int16')
#fit=[]
for i in range(0,6):
    #fit.append(fitness(ini[i]))
    f[i]=fitness(chromosomes[i])
print(f)

[91 59 69 64 84 72]


In [677]:
inv_f = np.zeros(pop_size)
inv_f = 1/(f+1)
print(inv_f)

p=np.zeros(pop_size)
p = inv_f/np.sum(inv_f)
print(p)
print(np.sum(p))

c=np.zeros(pop_size)
for i in range(0,pop_size):
    c[i]=np.sum(p[:(i+1)])
print(c)
r=np.random.rand(pop_size)
print(r)

[0.01086957 0.01666667 0.01428571 0.01538462 0.01176471 0.01369863]
[0.13148154 0.20160502 0.17280431 0.18609695 0.14230943 0.16570276]
1.0
[0.13148154 0.33308656 0.50589087 0.69198781 0.83429724 1.        ]
[0.78730952 0.3837846  0.59608264 0.05406084 0.67862534 0.7291427 ]


In [679]:
new_chromosomes = np.zeros((pop_size,ch_size),dtype='int16')
for i in range(0,pop_size):
    for j in range(0,pop_size):
        if (r[i] <= c[j]):
            new_chromosomes[i]=chromosomes[j]
            break

chromosomes=np.copy(new_chromosomes)
print(new_chromosomes)

[[14 14 24 12]
 [14 14 24 12]
 [27 21 26 17]
 [12 28 19 25]
 [27 21 26 17]
 [14 14 24 12]]


#### Crossover

In [686]:
ch=[]
ch_position=[]
crossover_pt=[]
for i in range(0,pop_size):
    r = random.random()
    if(r<pc):
        ch.append(chromosomes[i])
        ch_position.append(i)
print(ch)   
print(ch_position)
crossover_pt=np.random.randint(1,(ch_size),size=len(ch))
print(crossover_pt)
ch[0][1:3]

[array([12, 28, 19, 25], dtype=int16), array([27, 21, 26, 17], dtype=int16), array([14, 14, 24, 12], dtype=int16)]
[3, 4, 5]
[1 1 3]


array([28, 19], dtype=int16)

In [687]:
new_ch=[]
for i in range(0,len(ch)):
    new_ch.append(np.copy(ch[i]))
    if(i<len(ch)-1):
        new_ch[i][crossover_pt[i]:]=ch[i+1][crossover_pt[i]:].copy()
    else:
        new_ch[i][crossover_pt[i]:]=ch[0][crossover_pt[i]:].copy()
print(new_ch)
ch=new_ch.copy()

[array([12, 21, 26, 17], dtype=int16), array([27, 14, 24, 12], dtype=int16), array([14, 14, 24, 25], dtype=int16)]


In [688]:
for i in range(0,len(ch)):
    chromosomes[ch_position[i]]=np.copy(ch[i])
print(chromosomes)

[[14 14 24 12]
 [14 14 24 12]
 [27 21 26 17]
 [12 21 26 17]
 [27 14 24 12]
 [14 14 24 25]]


#### Mutation

In [689]:
def chromesome_gene_pos(x):
    ch_pos=int(x/ch_size)
    gene_pos=x%ch_size
    return ch_pos,gene_pos

In [646]:
mutation_range = pop_size* ch_size*pm
mutation_range = int(mutation_range)
num_of_mut = random.randrange(0,mutation_range+1)
print(mutation_range)
print(num_of_mut)

2
2


In [691]:
mut_values=np.random.randint(min_value,max_value,size=num_of_mut)
mut_pos=np.random.randint(0,(pop_size*ch_size),size=num_of_mut)
print(mut_pos)
print(mut_values)
for i in range(0,num_of_mut):
    ch_pos,gene_pos=chromesome_gene_pos(mut_pos[i])
    print(ch_pos,gene_pos)
    chromosomes[ch_pos,gene_pos]=mut_values[i].copy()

[ 3 15]
[14 15]
0 3
3 3


In [692]:
print('Updated Chromosomes')
print(chromosomes)
for i in range(0,6):
    #fit.append(fitness(ini[i]))
    f[i]=fitness(chromosomes[i])
print(f)

Updated Chromosomes
[[14 14 24 14]
 [25 14 24 12]
 [27 21 26 17]
 [12 21 26 15]
 [27 14 24 12]
 [14 14 24 19]]
[66 75 91 74 77 71]
