In [140]:
import numpy as np

In [141]:
def sigmoid(x):
    return 1/ (1+ np.exp(-x))
def sigmoid_derivative(x):
    return x * ( 1 - x )

In [149]:
no_of_iter =1
M = 10
N = 10
# train_ip = np.array([[0,0,1],
#          [1,1,1],
#          [1,0,1],
#          [0,1,1]])
# train_op = np.array([0,1,1,0]).reshape(M,1)
train_ip = np.random.randint(1,5,size=(M,N))
train_op = np.random.randint(0,2,size = (M,1))
train_op



array([[1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1]])

In [150]:
synaptic_weights = 2 * np.random.rand(N,1) - 1
print(synaptic_weights)
np.dot(input_layer,np.arange(1,M).reshape(N,1))
# input_layer* np.arange(1,4)

[[-0.96023973]
 [-0.94757803]
 [-0.94338702]
 [-0.50757786]
 [ 0.7200559 ]
 [ 0.07766213]
 [ 0.10564396]
 [ 0.68406178]
 [-0.75165337]
 [-0.44163264]]


ValueError: cannot reshape array of size 9 into shape (10,1)

In [163]:
for i in range(20000):
    input_layer = train_ip
    output = sigmoid(np.dot(input_layer,synaptic_weights))
    error = train_op - output
    adjustments = error * sigmoid_derivative(output)
    synaptic_weights += np.dot(input_layer.T, adjustments)
#     print('output after itereation',i,' ')
#     print(output)
#     print('Weights after itereation',i,' ')
#     print(synaptic_weights)

print('Exact Values after %d iterations' %(i+1))
print(output)

print('\nValues after rounding off')
print(np.around(output,decimals = 1))

print('\nWeights after %d iterations' %(i+1))
print(synaptic_weights)
    

Exact Values after 20000 iterations
[[0.99818261]
 [0.00144987]
 [1.        ]
 [0.99998816]
 [0.00140916]
 [1.        ]
 [0.99858089]
 [0.00145146]
 [0.99978368]
 [1.        ]]

Values after rounding off
[[1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]]

Weights after 20000 iterations
[[  3.59853494]
 [  1.45964684]
 [  3.1065206 ]
 [ -4.36206307]
 [  8.50833318]
 [  1.40187855]
 [ -2.60239652]
 [-11.3747921 ]
 [  5.61667264]
 [  1.8719289 ]]
